# Generated by Django 4.1.2 on 2023-06-30 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=20)),
                ('toppings', models.CharField(max_length=20)),
                ('add_ons', models.CharField(max_length=20)),
                ('time_of_order', models.DateTimeField(default=datetime.datetime(2023, 6, 30, 3, 42, 12, 52809, tzinfo=datetime.timezone.utc))),
                ('delivery', models.BooleanField(default=False)),
                ('is_order_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
