# Generated by Django 4.1.2 on 2023-06-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
